server:
  port: 8082

spring:
  application:
    name: artway-content-ms
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:5432/artway?currentSchema=artway_content
    username: postgres
    password: ${DB_PASSWORD:root}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://${HOST:localhost}:8761/eureka/
  instance:
    prefere-ip-address: true